import { Auth, User, Training, Task } from '../Constants.js';

export const SIGN_IN = `${Auth}/SIGN_IN`;
export const SIGN_IN_SUCCESS = `${Auth}/SIGN_IN_SUCCESS`;
export const SIGN_IN_ERROR = `${Auth}/SIGN_IN_ERROR`;

export const SIGN_OUT = `${Auth}/SIGN_OUT`;
export const SIGN_OUT_SUCCESS = `${Auth}/SIGN_OUT_SUCCESS`;
export const SIGN_OUT_ERROR = `${Auth}/SIGN_OUT_ERROR`;

export const FETCH_USER_INFO = `${User}/FETCH_USER_INFO`;
export const FETCH_USER_INFO_SUCCESS = `${User}/FETCH_USER_INFO_SUCCESS`;
export const FETCH_USER_INFO_ERROR = `${User}/FETCH_USER_INFO_ERROR`;

export const FETCH_TASK_COUNTS_DATA = `${Task}/FETCH_TASK_COUNTS_DATA`;
export const FETCH_TASK_COUNTS_DATA_SUCCESS = `${Task}/FETCH_TASK_COUNTS_DATA_SUCCESS`;
export const FETCH_TASK_COUNTS_DATA_ERROR = `${Task}/FETCH_TASK_COUNTS_DATA_ERROR`;

export const FETCH_SPELLCHECK_TASK = `${Task}/FETCH_SPELLCHECK_TASK`;
export const FETCH_SPELLCHECK_TASK_SUCCESS = `${Task}/FETCH_SPELLCHECK_TASK_SUCCESS`;
export const FETCH_SPELLCHECK_TASK_ERROR = `${Task}/FETCH_SPELLCHECK_TASK_ERROR`;

export const SAVE_SPELLCHECK_TASK_RESULT = `${Task}/SAVE_SPELLCHECK_TASK_RESULT_TASK`;
export const SAVE_SPELLCHECK_TASK_RESULT_SUCCESS = `${Task}/SAVE_SPELLCHECK_TASK_RESULT_SUCCESS`;
export const SAVE_SPELLCHECK_TASK_RESULT_ERROR = `${Task}/SAVE_SPELLCHECK_TASK_RESULT_ERROR`;

export const FETCH_IMAGE = `${Training}/FETCH_IMAGE`;
export const FETCH_IMAGE_ERROR = `${Training}/FETCH_IMAGE_ERROR`;

export const FETCH_TRAINING_DATA = `${Training}/FETCH_TRAINING_DATA`;
export const FETCH_TRAINING_DATA_SUCCESS = `${Training}/FETCH_TRAINING_DATA_SUCCESS`;
export const FETCH_TRAINING_DATA_ERROR = `${Training}/FETCH_TRAINING_DATA_ERROR`;

export const SELECT_AREA = `${Training}/SELECT_AREA`;

export const SAVE_TRAINING_DATA = `${Training}/SAVE_TRAINING_DATA`;
export const SAVE_TRAINING_DATA_ERROR = `${Training}/SAVE_TRAINING_DATA_ERROR`;

export const CHANGE_COORDS_TYPE = `${Training}/CHANGE_COORDS_TYPE`;
export const CHANGE_COORDS_TYPE_SUCCESS = `${Training}/CHANGE_COORDS_TYPE_SUCCESS`;
export const CHANGE_COORDS_TYPE_ERROR = `${Training}/CHANGE_COORDS_TYPE_ERROR`;
